# Generated by Django 2.2.6 on 2019-10-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_orm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simple',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='simple',
            name='url',
            field=models.URLField(default='Some defaults'),
        ),
    ]
