# Generated by Django 2.2.6 on 2019-10-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_orm', '0002_auto_20191009_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simple',
            name='url',
            field=models.URLField(default='www.example.com'),
        ),
    ]
