# Generated by Django 2.2.6 on 2019-10-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_orm', '0003_auto_20191009_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_date', models.DateTimeField()),
            ],
        ),
    ]
