# Generated by Django 2.2.6 on 2019-10-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_orm', '0004_dateexample'),
    ]

    operations = [
        migrations.CreateModel(
            name='NullExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
