# Generated by Django 2.2.6 on 2019-10-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_orm', '0007_character_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('feature_id', models.IntegerField(null=True)),
                ('feature', models.CharField(max_length=50)),
            ],
        ),
    ]
