# Generated by Django 2.2.6 on 2019-10-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_orm', '0008_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('features', models.ManyToManyField(to='db_orm.Feature')),
            ],
        ),
    ]
