# Generated by Django 2.2.6 on 2019-10-14 20:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db_orm', '0009_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureGroup',
            fields=[
                ('link', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AddField(
            model_name='product',
            name='balance',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='product',
            name='link',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_of_measurement',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='features',
            field=models.ManyToManyField(to='db_orm.FeatureGroup'),
        ),
        migrations.AddField(
            model_name='feature',
            name='feature_group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='db_orm.FeatureGroup'),
        ),
    ]
