# Generated by Django 2.2.6 on 2019-10-14 20:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db_orm', '0010_auto_20191014_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='feature_id',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='id',
        ),
        migrations.AddField(
            model_name='feature',
            name='link',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
