# Generated by Django 2.2.6 on 2019-10-14 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_orm', '0011_auto_20191014_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='features',
            field=models.ManyToManyField(to='db_orm.Feature'),
        ),
    ]
