# Generated by Django 2.2.6 on 2019-10-14 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_orm', '0012_auto_20191014_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='feature_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_orm.FeatureGroup'),
        ),
    ]
