# Generated by Django 2.2.6 on 2019-10-14 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_orm', '0014_auto_20191014_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='features_id',
            new_name='features_link',
        ),
    ]
