# Generated by Django 2.2.6 on 2019-10-14 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_orm', '0015_auto_20191014_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='feature',
        ),
    ]
