# Generated by Django 2.2.6 on 2019-10-14 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_orm', '0016_remove_feature_feature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='features_link',
        ),
    ]
