# Generated by Django 2.2.6 on 2019-10-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_orm', '0017_remove_product_features_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='features_link',
            field=models.ManyToManyField(to='db_orm.Feature'),
        ),
    ]
