# Generated by Django 2.2.6 on 2019-10-15 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_orm', '0018_product_features_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='feature_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db_orm.FeatureGroup'),
        ),
    ]
