# Generated by Django 2.2.6 on 2019-10-22 20:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db_orm', '0020_auto_20191015_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='ft_num',
            field=models.AutoField(default=None, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feature',
            name='link',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
