# Generated by Django 2.2.6 on 2019-10-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_orm', '0021_auto_20191022_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='ft_num',
        ),
        migrations.AddField(
            model_name='feature',
            name='num',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
