# Generated by Django 2.2.6 on 2019-10-22 21:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db_orm', '0022_auto_20191022_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='num',
        ),
        migrations.AlterField(
            model_name='feature',
            name='link',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
